# Generated by Django 5.0.6 on 2024-10-08 11:06

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_selection', models.CharField(choices=[('1', '1 час'), ('2', '2 часа'), ('3', '3 часа')], default='1', max_length=1)),
                ('datetime', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('booking', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, default='')),
                ('archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In processing', 'В обработке'), ('Cancelled', 'Отменено'), ('Booked', 'Забронировано'), ('Successfully', 'Успешно')], default='In processing', max_length=13)),
                ('rejection_text', models.TextField(default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation')),
            ],
        ),
    ]
